image: portal-common-docker.art.rambler.ru/builder

stages:
  - setup
  - build

before_script:
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - git config --global user.name "${GITLAB_USER_NAME}"

test:
  stage: setup
  tags:
    - docker
  except:
    - /^gh-pages/
  script:
    - npm install
    - npm run eslint
    - npm run test

build_site:
  stage: build
  tags:
    - docker
  except:
    - /gh-pages/
    - tags
  when: manual
  script:
    - npm install
    - ./ci-git-push-prepare.sh git@gitlab.rambler.ru/rambler-ui/rambler-ui
    - cd site
    - npm install
    - npm run gh-pages -- --omitGithub --versions "${CI_COMMIT_REF_NAME}"
    - cd ..

build_version:
  stage: build
  tags:
    - docker
  except:
    - /gh-pages/
  only:
    - tags
  when: manual
  script:
    - npm install
    - npm run build
    - cd build
    - curl -u${PROJECT_NPM_USER}:${PROJECT_NPM_AUTH_KEY} 'https://art.rambler.ru/api/npm/rambler-common/auth/rambler-common' > ~/.npmrc
    - node -e "var p=require('./package.json'); p.name='@rambler-common/rambler-ui'; p.publishConfig={registry:'https://art.rambler.ru/api/npm/rambler-common/'}; fs.writeFileSync('package.json', JSON.stringify(p, null, 2));"
    - cat ~/.npmrc
    - npm publish
    - rm ~/.npmrc
    - cd ..

build_version_site:
  stage: build
  tags:
    - docker
  except:
    - /gh-pages/
  only:
    - tags
  when: manual
  script:
    - npm install
    - ./ci-git-push-prepare.sh git@gitlab.rambler.ru/rambler-ui/rambler-ui
    - cd site
    - npm install
    - npm run gh-pages -- --omitGithub --versions "${CI_COMMIT_TAG}"
    - cd ..

pages:
  stage: setup
  tags:
    - docker
  only:
    - /gh-pages/
  script:
    - mkdir public
    - rsync -rv --exclude=.git --exclude=node_modules --exclude=public . ./public
  artifacts:
    untracked: false
    paths:
      - 'public'
